config/routes.rb
Rails.application.routes.draw do
  devise_for :actors
  root to: 'auditions#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :auditions do
    resources :participants, only: [:create, :destroy]
  end
  resources :actors

  namespace :api do
    namespace :v1 do
      resources :auditions, only: [:index]
      resources :actors
    end
  end
end

app/models/actor.rb
class Actor < ApplicationRecord
  has_many :participants
  has_many :auditions, through: :participants

  validates :name, presence: true, format: {
    with: /\A[a-zA-Z]+ [a-zA-Z]+\z/,
    message: 'must be a first name and last name!'
  }

  validates :email, uniqueness: true, format: {
    with: /\A([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)\z/,
    message: "isn't valid!"
  }

  validates :phone_number, presence: true, uniqueness: true, format: {
    with: /\A[\\(]{0,1}([0-9]){3}[\\)]{0,1}[ ]?([^0-1]){1}([0-9]){2}[ ]?[-]?[ ]?([0-9]){4}[ ]*((x){0,1}([0-9]){1,5}){0,1}\z/,
    message: "isn't valid!"
  }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/audition.rb
class Audition < ApplicationRecord
  has_many :roles
  has_many :participants
  has_many :actors, through: :participants

  validates :company, presence: true
end

app/models/director.rb
class Director < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/participant.rb
class Participant < ApplicationRecord
  belongs_to :audition
  belongs_to :actor
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :audition
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, format: {
    with: /\A[a-zA-Z]+ [a-zA-Z]+\z/,
    message: 'must be a first name and last name!'
  }

  validates :email, uniqueness: true, format: {
    with: /\A([a-zA-Z0-9_\-\.]+)@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.)|(([a-zA-Z0-9\-]+\.)+))([a-zA-Z]{2,4}|[0-9]{1,3})(\]?)\z/,
    message: "isn't valid!"
  }

  validates :phone_number, presence: true, uniqueness: true, format: {
    with: /\A[\\(]{0,1}([0-9]){3}[\\)]{0,1}[ ]?([^0-1]){1}([0-9]){2}[ ]?[-]?[ ]?([0-9]){4}[ ]*((x){0,1}([0-9]){1,5}){0,1}\z/,
    message: "isn't valid!"
  }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/actors_controller.rb
class ActorsController < ApplicationController
  def show
    @actor = current_actor
    auditions = @actor.auditions
    auditions.sort_by { |aud| aud.date }
    @past_auditions = auditions.find_all { |audition| audition.date < Time.now() }
    @past_auditions = @past_auditions.sort_by { |aud| aud.date }
    @future_auditions = auditions.find_all { |audition| audition.date >= Time.now() }
    @future_auditions = @future_auditions.sort_by { |aud| aud.date }
  end
end

app/controllers/api/v1/actors_controller.rb
class Api::V1::ActorsController < ApplicationController
  def index
    render json: current_actor
  end
end

app/controllers/api/v1/auditions_controller.rb
class Api::V1::AuditionsController < ApplicationController

  def index
    if actor_signed_in?
      render json: { actor: current_actor, auditions: Audition.all, signedIn: true }
    else
      render json: { actor: Actor.where(name: 'dumb dumb').first, auditions: Audition.all, signedIn: false }
    end
  end
end

app/controllers/api/v1/votes_controller.rb
class Api::V1::VotesController < ApplicationController
  def create
    review = Review.find(params[:review_id])
    if !Vote.where(user: current_user, review: review).empty?
      old_vote = Vote.where(user: current_user, review: review).first
      if old_vote.upvote.to_s != params[:vote]
        old_vote.update(upvote: params[:vote])
      end
    else
      vote = Vote.create(review: review, user: current_user, upvote: params[:vote])
    end
    # VoteMailer.new_vote(vote).deliver_now
    render json: { score: review.score }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(
      :sign_up,
      keys: [
        :name,
        :password,
        :email,
        :phone_number,
        :gender,
        :age,
        :ethnicity
      ]
    )
  end
end

app/controllers/auditions_controller.rb
class AuditionsController < ApplicationController
  def index
    @auditions = Audition.all
    @auditions = @auditions.order(:date)

    @actor = current_actor
  end

  def show
    @audition = Audition.find(params[:id])
    if @audition.company.include?(';')
        @crew = @audition.company.split(';')
    elsif @audition.company.include?(',') && !@audition.company.include?(';')
        @crew = @audition.company.split(',')
    else
        @crew = [ @audition.company ]
    end
    @centered = ''
    if @audition.roles.size % 2 == 1
      @centered = 'small-centered'
    end
    @actor = current_actor
    @actors = @audition.actors

  end

  def new # save for Director implementation
    @audition = Audition.new
    @actor = current_actor
  end

  def create # save for Director implementation
    @audition = Audition.create(strong_params)
    @audition.creator = current_actor.name
    @audition.actors << current_actor
    if @audition.save
      flash[:notice] = "Audition Posted"
      redirect_to root_path
    else
      flash[:alert] = "Audition Not Posted!"
      render 'new'
    end
  end

  def edit # save for Director implementation
    @audition = Audition.find(params[:id])
    @actor = current_actor
  end

  def update # save for Director implementation
    @audition = Audition.find(params[:id])
    if @audition.update_attributes(strong_params)
      flash[:notice] = 'Audition information updated.'
      redirect_to @audition
    else
      flash[:notice] = @audition.errors.messages
      render action: 'edit'
    end
  end

  def destroy # save for Director implementation
    @audition = Audition.find(params[:id])
    @audition.delete

    flash[:notice] = "Audition Deleted"
    redirect_to root_path
  end

  private

  def review_params
    params.require(:audition).permit(
      :roles,
      :show,
      :theater,
      :address,
      :company,
      :description,
      :equity,
      :date
    )
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/participants_controller.rb
class ParticipantsController < ApplicationController
  def create
    audition = Audition.find(params[:audition_id])
    participant = Participant.create(audition: audition, actor: current_actor)
    if participant.save
      redirect_to audition_path(audition), notice: "Audition added to your List"
    else
      redirect_to audition_path(audition), alert: "Audition Not Saved!"
    end
  end

  def destroy
    audition = Audition.find(params[:audition_id])
    participant = Participant.where(audition: audition, actor: current_actor).first
    if participant.destroy
      redirect_to audition_path(audition), notice: "Audition Removed from your List"
    else
      redirect_to audition_path(audition), alert: "Audition Not Removed!"
    end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def destroy
    super
  end
end

app/helpers/actor_helper.rb
module ActorHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/particpant_helper.rb
module ParticpantHelper
end

app/views/actors/show.html.erb
<div class="row" id="profile_page">
  <h1><%= @actor.name %></h1>
  <h3>Age: <%= @actor.age %></h3>
  <h3>Ethnicity: <%= @actor.ethnicity %></h3>
  <h3>Gender: <%= @actor.gender %></h3>
  <h2>Auditions</h2>
  <% if !@past_auditions.empty? %>
    <h3>Past Auditions</h3>
    <ul>
      <% @past_auditions.each do |audition| %>
        <li><%= link_to "#{audition.show}, #{audition.date.strftime("%B %e")}", audition_path(audition) %></li>
      <% end %>
    </ul>
  <% end %>

  <% if !@future_auditions.empty? %>
    <h3>Current Auditions</h3>
      <% @future_auditions.each do |audition| %>
        <h5> - <%= link_to "#{audition.show}, #{audition.date.strftime("%B %e")}", audition_path(audition) %></h5>
      <% end %>
  <% else %>
    <h4>No Upcoming Auditions. Keep Looking!</h4>
  <% end %>
</div>

app/views/auditions/index.html.erb
<h1 id="header">Star Matcher</h1>
<div id="app">
  loading
</div>

app/views/auditions/show.html.erb
<div id="show-header">
  <h2 class="row text-center"><%= @audition.show %></h2>
</div>

<div class="row">
  <div class="large-6 small-12 columns" id="show_left_info_box">
    <h3>Date: <%= @audition.date.strftime("%e %B") %></h3>
    <% if @audition.equity %><h3>Equity</h3><% else %><h3>Not Equity</h3><% end %>
    <h4><%= @audition.theater %></h4>
    <h4><%= @audition.address %></h4>
    <div id="crew_container">
      <h4>Crew</h4>
      <ul>
        <% @crew.each do |crew_member| %>
          <li><%= crew_member %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="large-6 small-12 text-center columns" id="show_right_info_box">
    <% if current_actor %>
      <% if !current_actor.auditions.include?(@audition) %>
        <%= button_to "Save Audition", audition_participants_path(@audition), class: "button" %>
      <% else %>
        <%= button_to "Remove Audition", audition_participant_path(@audition), method: :delete, class: "button row text-center" %>
      <% end %>
    <% else %>
      <h3>Sign in to save this audition!</h1>
    <% end %>
    <p><%= @audition.description %></p>
  </div>
</div>

<div class="text-center">
  <% if @actors.size > 0 %>
    <h2>Interested Actors</h2>
    <ul>
      <% @actors.each do |actor| %>
        <li><%= link_to actor.name, actor_path(actor) %></li>
      <% end %>
    </ul>
  <% end %>
</div>

<div class="row text-center">
  <h3>Roles</h3>
  <% @audition.roles.each do |role| %>
    <% if role != @audition.roles.last %>
      <div class="large-6 small-12 columns" id="show_roles_column_container">
    <% else %>
      <div class="large-6 small-12 columns end" id="show_roles_column_container">
    <% end %>
      <div id="show_role_tile">
        <h4><%= role.title %></h4>
        <h5>Age: <%= role.age_min %>-<%= role.age_max %></h5>
        <h5>Ethnicity: <%= role.ethnicity %></h5>
        <div class="role_description">
          <p><%= role.description %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="row">
  <% if current_user %>
    <div class="col-sm-12 text-xs-center bootstrap-welcome">
      <h1>Welcome <%= current_user.email %></h1>
      <p><%= link_to 'edit profile', edit_user_registration_path(current_user) %></p>
      <p><%= link_to('Logout', destroy_user_session_path, method: :delete) %></p>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Star Matcher" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Francois+One|PT+Sans|Quicksand:500" rel="stylesheet">
  </head>

  <body>
    <div class="top-bar">
      <div class="top-bar-left">
        <ul class="menu">
          <li>
            <a href="/">Auditions</a>
          </li>
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu">
          <% if actor_signed_in? %>
            <li><%= link_to "Sign Out", destroy_actor_session_path, method: :delete %></li>
            <li><%= link_to "My Profile", actor_path(current_actor) %></li>
          <% else %>
            <li><%= link_to "Create Account", new_actor_registration_path%></li>
            <li><%= link_to "Sign In", new_actor_session_path%></li>
          <% end %>
        </ul>
      </div>
    </div>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <%= yield %>

  </body>
</html>